### ISSUE TITLE
Handle component children

### ISSUE THREAD

**Issue by GlassBricks** [bnorm/kotlin-react-function#9]
Right now, using something like `block: RBuilder.()->Unit` to pass children to a RFunction doesn't work properly (the lambda is treated as a property, react hooks in child components break).
(Also, the sample project breaks because of this).

Instead, children can be handled by turning such a lambda call into `props.children()`, and invoking the lambda in the generated handler:

```kotlin
@RFunction
fun RBuilder.Hello(name: String, children: RBuilder.() -> Unit) {
  +"Hello, $name"
  div {
    children()
  }
}
```
transformed into something like
```kotlin
private val HELLO_COMPONENT = rFunction<HelloProps>("Hello") { props ->
  +"Hello, ${props.name}"
  div {
    props.children()
  }
}

fun RBuilder.Hello(name: String, children: RBuilder.() -> Unit) {
  HELLO_COMPONENT.invoke {
    attrs.name = name
    children()
  }
//or, more directly:
  child(HELLO_COMPONENT, jsObject<HelloProps> {
    this.name = name
  }, children)
}
```

**Comment by GlassBricks** [comment]
Also, there should probably be a way to distinguish the children handler from lambda properties:
- With an annotation:
```kotlin
fun RBuilder.Hello(name: String, @RChildren children: RBuilder.() -> Unit) {
```
- With a special typealias
```kotlin
// in library dependency
typealias RChildren = RBuilder.() -> Unit
// -----
fun RBuilder.Hello(name: String, children: RChildren) {
```
I'm leaning towards the latter.


I'm new to kotlin IR, but if this is confirmed I can give a stab at a PR for this.

**Comment by bnorm** [comment]
First off, thanks for trying this library and providing feedback! I really appreciate it!

Could you describe more what you mean by the sample project breaks because of this? Which react hooks do not work? How are they not working? The [live version of the sample project](https://bnorm.github.io/kotlin-react-function/) seems to be working and it is built from the latest version of this library. If you made a change to the sample project which caused it to no longer work, could you create a PR showing those changes?

This potential problem had occurred to me and my solution was going to be a `@RChildren` annotation. However I've not encountered any problems with this property vs children behavior so I didn't think it was going to be an issue. If you can provide some more details we can work towards a proper solution.

**Comment by GlassBricks** [comment]
The sample project breaks with no changes, only in development mode, however I incorrectly assumed it was because of the children prop issue. After lots of debugging I found that it breaks due to an entirely different reason with styled components, not related to this library.

Also, some investigation reveals that children are simply handled as a special property, so the current behavior is _probably_ ok. Maybe this can be added to documentation.

So, closing this issue for now.

Side note:
using `react.Children` functions is possible but a bit unobvious. Perhaps add this to documentation:
```kotlin
val children = buildElements { block() }
Children.xxx(children, ...)
```
